(cl:defpackage context_action_framework-srv
  (:use )
  (:export
   "NEXTACTION"
   "<NEXTACTION-REQUEST>"
   "NEXTACTION-REQUEST"
   "<NEXTACTION-RESPONSE>"
   "NEXTACTION-RESPONSE"
   "VISIONDETECTION"
   "<VISIONDETECTION-REQUEST>"
   "VISIONDETECTION-REQUEST"
   "<VISIONDETECTION-RESPONSE>"
   "VISIONDETECTION-RESPONSE"
  ))

