(cl:defpackage dnb_msgs-msg
  (:use )
  (:export
   "<ARGUMENT>"
   "ARGUMENT"
   "<COMPONENTSTATUS>"
   "COMPONENTSTATUS"
   "<DATASTOREEXTERNALENTRY>"
   "DATASTOREEXTERNALENTRY"
   "<DATASTOREEXTERNALSOURCEUPDATE>"
   "DATASTOREEXTERNALSOURCEUPDATE"
   "<KETOPSTATUS>"
   "KETOPSTATUS"
   "<PROGRAM>"
   "PROGRAM"
   "<STRINGMULTIARRAY>"
   "STRINGMULTIARRAY"
   "<TOASTMESSAGE>"
   "TOASTMESSAGE"
   "<TOASTTRANSLATION>"
   "TOASTTRANSLATION"
  ))

