// Generated by gencpp from file camera_control_msgs/GetFloatValueRequest.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_GETFLOATVALUEREQUEST_H
#define CAMERA_CONTROL_MSGS_MESSAGE_GETFLOATVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_control_msgs
{
template <class ContainerAllocator>
struct GetFloatValueRequest_
{
  typedef GetFloatValueRequest_<ContainerAllocator> Type;

  GetFloatValueRequest_()
    {
    }
  GetFloatValueRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFloatValueRequest_

typedef ::camera_control_msgs::GetFloatValueRequest_<std::allocator<void> > GetFloatValueRequest;

typedef boost::shared_ptr< ::camera_control_msgs::GetFloatValueRequest > GetFloatValueRequestPtr;
typedef boost::shared_ptr< ::camera_control_msgs::GetFloatValueRequest const> GetFloatValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace camera_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_control_msgs/GetFloatValueRequest";
  }

  static const char* value(const ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFloatValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::camera_control_msgs::GetFloatValueRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_GETFLOATVALUEREQUEST_H
