// Generated by gencpp from file camera_control_msgs/GetIntegerValue.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_GETINTEGERVALUE_H
#define CAMERA_CONTROL_MSGS_MESSAGE_GETINTEGERVALUE_H

#include <ros/service_traits.h>


#include <camera_control_msgs/GetIntegerValueRequest.h>
#include <camera_control_msgs/GetIntegerValueResponse.h>


namespace camera_control_msgs
{

struct GetIntegerValue
{

typedef GetIntegerValueRequest Request;
typedef GetIntegerValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIntegerValue
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::GetIntegerValue > {
  static const char* value()
  {
    return "2e594fdfa2675fb84aef8c993fb08db4";
  }

  static const char* value(const ::camera_control_msgs::GetIntegerValue&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::GetIntegerValue > {
  static const char* value()
  {
    return "camera_control_msgs/GetIntegerValue";
  }

  static const char* value(const ::camera_control_msgs::GetIntegerValue&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::GetIntegerValueRequest> should match
// service_traits::MD5Sum< ::camera_control_msgs::GetIntegerValue >
template<>
struct MD5Sum< ::camera_control_msgs::GetIntegerValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::GetIntegerValue >::value();
  }
  static const char* value(const ::camera_control_msgs::GetIntegerValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::GetIntegerValueRequest> should match
// service_traits::DataType< ::camera_control_msgs::GetIntegerValue >
template<>
struct DataType< ::camera_control_msgs::GetIntegerValueRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::GetIntegerValue >::value();
  }
  static const char* value(const ::camera_control_msgs::GetIntegerValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::GetIntegerValueResponse> should match
// service_traits::MD5Sum< ::camera_control_msgs::GetIntegerValue >
template<>
struct MD5Sum< ::camera_control_msgs::GetIntegerValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::GetIntegerValue >::value();
  }
  static const char* value(const ::camera_control_msgs::GetIntegerValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::GetIntegerValueResponse> should match
// service_traits::DataType< ::camera_control_msgs::GetIntegerValue >
template<>
struct DataType< ::camera_control_msgs::GetIntegerValueResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::GetIntegerValue >::value();
  }
  static const char* value(const ::camera_control_msgs::GetIntegerValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_GETINTEGERVALUE_H
