// Generated by gencpp from file camera_control_msgs/SetWhiteBalance.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETWHITEBALANCE_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETWHITEBALANCE_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetWhiteBalanceRequest.h>
#include <camera_control_msgs/SetWhiteBalanceResponse.h>


namespace camera_control_msgs
{

struct SetWhiteBalance
{

typedef SetWhiteBalanceRequest Request;
typedef SetWhiteBalanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWhiteBalance
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetWhiteBalance > {
  static const char* value()
  {
    return "fdbb1487027d9369a9a369523a030ac9";
  }

  static const char* value(const ::camera_control_msgs::SetWhiteBalance&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetWhiteBalance > {
  static const char* value()
  {
    return "camera_control_msgs/SetWhiteBalance";
  }

  static const char* value(const ::camera_control_msgs::SetWhiteBalance&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetWhiteBalanceRequest> should match
// service_traits::MD5Sum< ::camera_control_msgs::SetWhiteBalance >
template<>
struct MD5Sum< ::camera_control_msgs::SetWhiteBalanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetWhiteBalance >::value();
  }
  static const char* value(const ::camera_control_msgs::SetWhiteBalanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetWhiteBalanceRequest> should match
// service_traits::DataType< ::camera_control_msgs::SetWhiteBalance >
template<>
struct DataType< ::camera_control_msgs::SetWhiteBalanceRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetWhiteBalance >::value();
  }
  static const char* value(const ::camera_control_msgs::SetWhiteBalanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetWhiteBalanceResponse> should match
// service_traits::MD5Sum< ::camera_control_msgs::SetWhiteBalance >
template<>
struct MD5Sum< ::camera_control_msgs::SetWhiteBalanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetWhiteBalance >::value();
  }
  static const char* value(const ::camera_control_msgs::SetWhiteBalanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetWhiteBalanceResponse> should match
// service_traits::DataType< ::camera_control_msgs::SetWhiteBalance >
template<>
struct DataType< ::camera_control_msgs::SetWhiteBalanceResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetWhiteBalance >::value();
  }
  static const char* value(const ::camera_control_msgs::SetWhiteBalanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETWHITEBALANCE_H
