// Generated by gencpp from file dnb_msgs/ConfigureDatastoreExternalSourceRequest.msg
// DO NOT EDIT!


#ifndef DNB_MSGS_MESSAGE_CONFIGUREDATASTOREEXTERNALSOURCEREQUEST_H
#define DNB_MSGS_MESSAGE_CONFIGUREDATASTOREEXTERNALSOURCEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dnb_msgs/DatastoreExternalEntry.h>

namespace dnb_msgs
{
template <class ContainerAllocator>
struct ConfigureDatastoreExternalSourceRequest_
{
  typedef ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> Type;

  ConfigureDatastoreExternalSourceRequest_()
    : source()
    , entries()  {
    }
  ConfigureDatastoreExternalSourceRequest_(const ContainerAllocator& _alloc)
    : source(_alloc)
    , entries(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;

   typedef std::vector< ::dnb_msgs::DatastoreExternalEntry_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dnb_msgs::DatastoreExternalEntry_<ContainerAllocator> >> _entries_type;
  _entries_type entries;





  typedef boost::shared_ptr< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigureDatastoreExternalSourceRequest_

typedef ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<std::allocator<void> > ConfigureDatastoreExternalSourceRequest;

typedef boost::shared_ptr< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest > ConfigureDatastoreExternalSourceRequestPtr;
typedef boost::shared_ptr< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest const> ConfigureDatastoreExternalSourceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator1> & lhs, const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.source == rhs.source &&
    lhs.entries == rhs.entries;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator1> & lhs, const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dnb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c227c9fdc93e0c3a5ee90f54bf35910a";
  }

  static const char* value(const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc227c9fdc93e0c3aULL;
  static const uint64_t static_value2 = 0x5ee90f54bf35910aULL;
};

template<class ContainerAllocator>
struct DataType< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dnb_msgs/ConfigureDatastoreExternalSourceRequest";
  }

  static const char* value(const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string source\n"
"DatastoreExternalEntry[] entries\n"
"\n"
"================================================================================\n"
"MSG: dnb_msgs/DatastoreExternalEntry\n"
"string source\n"
"string source_id\n"
"string value\n"
"string type\n"
"string display_title\n"
"bool editable\n"
;
  }

  static const char* value(const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
      stream.next(m.entries);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigureDatastoreExternalSourceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dnb_msgs::ConfigureDatastoreExternalSourceRequest_<ContainerAllocator>& v)
  {
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
    s << indent << "entries[]" << std::endl;
    for (size_t i = 0; i < v.entries.size(); ++i)
    {
      s << indent << "  entries[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dnb_msgs::DatastoreExternalEntry_<ContainerAllocator> >::stream(s, indent + "    ", v.entries[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNB_MSGS_MESSAGE_CONFIGUREDATASTOREEXTERNALSOURCEREQUEST_H
