// Generated by gencpp from file dnb_msgs/RunProgramWithArguments.msg
// DO NOT EDIT!


#ifndef DNB_MSGS_MESSAGE_RUNPROGRAMWITHARGUMENTS_H
#define DNB_MSGS_MESSAGE_RUNPROGRAMWITHARGUMENTS_H

#include <ros/service_traits.h>


#include <dnb_msgs/RunProgramWithArgumentsRequest.h>
#include <dnb_msgs/RunProgramWithArgumentsResponse.h>


namespace dnb_msgs
{

struct RunProgramWithArguments
{

typedef RunProgramWithArgumentsRequest Request;
typedef RunProgramWithArgumentsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunProgramWithArguments
} // namespace dnb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dnb_msgs::RunProgramWithArguments > {
  static const char* value()
  {
    return "98a81ff4cecb846b0a97bc6aa8107d97";
  }

  static const char* value(const ::dnb_msgs::RunProgramWithArguments&) { return value(); }
};

template<>
struct DataType< ::dnb_msgs::RunProgramWithArguments > {
  static const char* value()
  {
    return "dnb_msgs/RunProgramWithArguments";
  }

  static const char* value(const ::dnb_msgs::RunProgramWithArguments&) { return value(); }
};


// service_traits::MD5Sum< ::dnb_msgs::RunProgramWithArgumentsRequest> should match
// service_traits::MD5Sum< ::dnb_msgs::RunProgramWithArguments >
template<>
struct MD5Sum< ::dnb_msgs::RunProgramWithArgumentsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dnb_msgs::RunProgramWithArguments >::value();
  }
  static const char* value(const ::dnb_msgs::RunProgramWithArgumentsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dnb_msgs::RunProgramWithArgumentsRequest> should match
// service_traits::DataType< ::dnb_msgs::RunProgramWithArguments >
template<>
struct DataType< ::dnb_msgs::RunProgramWithArgumentsRequest>
{
  static const char* value()
  {
    return DataType< ::dnb_msgs::RunProgramWithArguments >::value();
  }
  static const char* value(const ::dnb_msgs::RunProgramWithArgumentsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dnb_msgs::RunProgramWithArgumentsResponse> should match
// service_traits::MD5Sum< ::dnb_msgs::RunProgramWithArguments >
template<>
struct MD5Sum< ::dnb_msgs::RunProgramWithArgumentsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dnb_msgs::RunProgramWithArguments >::value();
  }
  static const char* value(const ::dnb_msgs::RunProgramWithArgumentsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dnb_msgs::RunProgramWithArgumentsResponse> should match
// service_traits::DataType< ::dnb_msgs::RunProgramWithArguments >
template<>
struct DataType< ::dnb_msgs::RunProgramWithArgumentsResponse>
{
  static const char* value()
  {
    return DataType< ::dnb_msgs::RunProgramWithArguments >::value();
  }
  static const char* value(const ::dnb_msgs::RunProgramWithArgumentsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DNB_MSGS_MESSAGE_RUNPROGRAMWITHARGUMENTS_H
