# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from context_action_framework/ViceBlock.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ViceBlock(genpy.Message):
  _md5sum = "8bc5ee0d433fee744520e4f066921b9b"
  _type = "context_action_framework/ViceBlock"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Module enum
int8 module

bool clamp

bool turn_over
"""
  __slots__ = ['module','clamp','turn_over']
  _slot_types = ['int8','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       module,clamp,turn_over

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ViceBlock, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.module is None:
        self.module = 0
      if self.clamp is None:
        self.clamp = False
      if self.turn_over is None:
        self.turn_over = False
    else:
      self.module = 0
      self.clamp = False
      self.turn_over = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b2B().pack(_x.module, _x.clamp, _x.turn_over))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.module, _x.clamp, _x.turn_over,) = _get_struct_b2B().unpack(str[start:end])
      self.clamp = bool(self.clamp)
      self.turn_over = bool(self.turn_over)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b2B().pack(_x.module, _x.clamp, _x.turn_over))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.module, _x.clamp, _x.turn_over,) = _get_struct_b2B().unpack(str[start:end])
      self.clamp = bool(self.clamp)
      self.turn_over = bool(self.turn_over)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b2B = None
def _get_struct_b2B():
    global _struct_b2B
    if _struct_b2B is None:
        _struct_b2B = struct.Struct("<b2B")
    return _struct_b2B
