// Generated by gencpp from file context_action_framework/Gaps.msg
// DO NOT EDIT!


#ifndef CONTEXT_ACTION_FRAMEWORK_MESSAGE_GAPS_H
#define CONTEXT_ACTION_FRAMEWORK_MESSAGE_GAPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <context_action_framework/Gap.h>

namespace context_action_framework
{
template <class ContainerAllocator>
struct Gaps_
{
  typedef Gaps_<ContainerAllocator> Type;

  Gaps_()
    : header()
    , gaps()  {
    }
  Gaps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gaps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::context_action_framework::Gap_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::context_action_framework::Gap_<ContainerAllocator> >> _gaps_type;
  _gaps_type gaps;





  typedef boost::shared_ptr< ::context_action_framework::Gaps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::context_action_framework::Gaps_<ContainerAllocator> const> ConstPtr;

}; // struct Gaps_

typedef ::context_action_framework::Gaps_<std::allocator<void> > Gaps;

typedef boost::shared_ptr< ::context_action_framework::Gaps > GapsPtr;
typedef boost::shared_ptr< ::context_action_framework::Gaps const> GapsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::context_action_framework::Gaps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::context_action_framework::Gaps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::context_action_framework::Gaps_<ContainerAllocator1> & lhs, const ::context_action_framework::Gaps_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gaps == rhs.gaps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::context_action_framework::Gaps_<ContainerAllocator1> & lhs, const ::context_action_framework::Gaps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace context_action_framework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::context_action_framework::Gaps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::context_action_framework::Gaps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::context_action_framework::Gaps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::context_action_framework::Gaps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::context_action_framework::Gaps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::context_action_framework::Gaps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::context_action_framework::Gaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ec64f888e2c36be2e073dca5408e8c9";
  }

  static const char* value(const ::context_action_framework::Gaps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ec64f888e2c36beULL;
  static const uint64_t static_value2 = 0x2e073dca5408e8c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::context_action_framework::Gaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "context_action_framework/Gaps";
  }

  static const char* value(const ::context_action_framework::Gaps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::context_action_framework::Gaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"context_action_framework/Gap[] gaps\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: context_action_framework/Gap\n"
"int8 id\n"
"\n"
"# transform start of levering\n"
"geometry_msgs/Transform from_tf\n"
"\n"
"# transform end of levering\n"
"geometry_msgs/Transform to_tf\n"
"\n"
"# depth in meters\n"
"float32 from_depth\n"
"float32 to_depth\n"
"\n"
"# on which detection does the levering start\n"
"# context_action_framework/Detection from_det\n"
"\n"
"# on/in which detection does the levering end\n"
"# context_action_framework/Detection to_det\n"
"\n"
"# oriented bounding box of gap (meters)\n"
"float32[] obb\n"
"\n"
"# 3d oriented bounding box of gap (meters)\n"
"float32[] obb_3d\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::context_action_framework::Gaps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::context_action_framework::Gaps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gaps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gaps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::context_action_framework::Gaps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::context_action_framework::Gaps_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gaps[]" << std::endl;
    for (size_t i = 0; i < v.gaps.size(); ++i)
    {
      s << indent << "  gaps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::context_action_framework::Gap_<ContainerAllocator> >::stream(s, indent + "    ", v.gaps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTEXT_ACTION_FRAMEWORK_MESSAGE_GAPS_H
