// Generated by gencpp from file context_action_framework/NextAction.msg
// DO NOT EDIT!


#ifndef CONTEXT_ACTION_FRAMEWORK_MESSAGE_NEXTACTION_H
#define CONTEXT_ACTION_FRAMEWORK_MESSAGE_NEXTACTION_H

#include <ros/service_traits.h>


#include <context_action_framework/NextActionRequest.h>
#include <context_action_framework/NextActionResponse.h>


namespace context_action_framework
{

struct NextAction
{

typedef NextActionRequest Request;
typedef NextActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NextAction
} // namespace context_action_framework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::context_action_framework::NextAction > {
  static const char* value()
  {
    return "02efeedcf42ee81f7c89e3d3ea2145e9";
  }

  static const char* value(const ::context_action_framework::NextAction&) { return value(); }
};

template<>
struct DataType< ::context_action_framework::NextAction > {
  static const char* value()
  {
    return "context_action_framework/NextAction";
  }

  static const char* value(const ::context_action_framework::NextAction&) { return value(); }
};


// service_traits::MD5Sum< ::context_action_framework::NextActionRequest> should match
// service_traits::MD5Sum< ::context_action_framework::NextAction >
template<>
struct MD5Sum< ::context_action_framework::NextActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::context_action_framework::NextAction >::value();
  }
  static const char* value(const ::context_action_framework::NextActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::context_action_framework::NextActionRequest> should match
// service_traits::DataType< ::context_action_framework::NextAction >
template<>
struct DataType< ::context_action_framework::NextActionRequest>
{
  static const char* value()
  {
    return DataType< ::context_action_framework::NextAction >::value();
  }
  static const char* value(const ::context_action_framework::NextActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::context_action_framework::NextActionResponse> should match
// service_traits::MD5Sum< ::context_action_framework::NextAction >
template<>
struct MD5Sum< ::context_action_framework::NextActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::context_action_framework::NextAction >::value();
  }
  static const char* value(const ::context_action_framework::NextActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::context_action_framework::NextActionResponse> should match
// service_traits::DataType< ::context_action_framework::NextAction >
template<>
struct DataType< ::context_action_framework::NextActionResponse>
{
  static const char* value()
  {
    return DataType< ::context_action_framework::NextAction >::value();
  }
  static const char* value(const ::context_action_framework::NextActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTEXT_ACTION_FRAMEWORK_MESSAGE_NEXTACTION_H
