// Generated by gencpp from file context_action_framework/VisionBlock.msg
// DO NOT EDIT!


#ifndef CONTEXT_ACTION_FRAMEWORK_MESSAGE_VISIONBLOCK_H
#define CONTEXT_ACTION_FRAMEWORK_MESSAGE_VISIONBLOCK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Transform.h>

namespace context_action_framework
{
template <class ContainerAllocator>
struct VisionBlock_
{
  typedef VisionBlock_<ContainerAllocator> Type;

  VisionBlock_()
    : camera(0)
    , module(0)
    , tf()
    , gap_detection(false)  {
    }
  VisionBlock_(const ContainerAllocator& _alloc)
    : camera(0)
    , module(0)
    , tf(_alloc)
    , gap_detection(false)  {
  (void)_alloc;
    }



   typedef int8_t _camera_type;
  _camera_type camera;

   typedef int8_t _module_type;
  _module_type module;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _tf_type;
  _tf_type tf;

   typedef uint8_t _gap_detection_type;
  _gap_detection_type gap_detection;





  typedef boost::shared_ptr< ::context_action_framework::VisionBlock_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::context_action_framework::VisionBlock_<ContainerAllocator> const> ConstPtr;

}; // struct VisionBlock_

typedef ::context_action_framework::VisionBlock_<std::allocator<void> > VisionBlock;

typedef boost::shared_ptr< ::context_action_framework::VisionBlock > VisionBlockPtr;
typedef boost::shared_ptr< ::context_action_framework::VisionBlock const> VisionBlockConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::context_action_framework::VisionBlock_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::context_action_framework::VisionBlock_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::context_action_framework::VisionBlock_<ContainerAllocator1> & lhs, const ::context_action_framework::VisionBlock_<ContainerAllocator2> & rhs)
{
  return lhs.camera == rhs.camera &&
    lhs.module == rhs.module &&
    lhs.tf == rhs.tf &&
    lhs.gap_detection == rhs.gap_detection;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::context_action_framework::VisionBlock_<ContainerAllocator1> & lhs, const ::context_action_framework::VisionBlock_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace context_action_framework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::context_action_framework::VisionBlock_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::context_action_framework::VisionBlock_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::context_action_framework::VisionBlock_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::context_action_framework::VisionBlock_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::context_action_framework::VisionBlock_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::context_action_framework::VisionBlock_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::context_action_framework::VisionBlock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f331af18bd7868ca6460c04549f4c84";
  }

  static const char* value(const ::context_action_framework::VisionBlock_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f331af18bd7868cULL;
  static const uint64_t static_value2 = 0xa6460c04549f4c84ULL;
};

template<class ContainerAllocator>
struct DataType< ::context_action_framework::VisionBlock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "context_action_framework/VisionBlock";
  }

  static const char* value(const ::context_action_framework::VisionBlock_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::context_action_framework::VisionBlock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Camera enum\n"
"int8 camera\n"
"\n"
"# Module enum\n"
"int8 module\n"
"\n"
"# camera transform\n"
"geometry_msgs/Transform tf\n"
"\n"
"# request gap detection True/False\n"
"bool gap_detection\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::context_action_framework::VisionBlock_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::context_action_framework::VisionBlock_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera);
      stream.next(m.module);
      stream.next(m.tf);
      stream.next(m.gap_detection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionBlock_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::context_action_framework::VisionBlock_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::context_action_framework::VisionBlock_<ContainerAllocator>& v)
  {
    s << indent << "camera: ";
    Printer<int8_t>::stream(s, indent + "  ", v.camera);
    s << indent << "module: ";
    Printer<int8_t>::stream(s, indent + "  ", v.module);
    s << indent << "tf: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.tf);
    s << indent << "gap_detection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gap_detection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTEXT_ACTION_FRAMEWORK_MESSAGE_VISIONBLOCK_H
