// Generated by gencpp from file context_action_framework/VisionDetection.msg
// DO NOT EDIT!


#ifndef CONTEXT_ACTION_FRAMEWORK_MESSAGE_VISIONDETECTION_H
#define CONTEXT_ACTION_FRAMEWORK_MESSAGE_VISIONDETECTION_H

#include <ros/service_traits.h>


#include <context_action_framework/VisionDetectionRequest.h>
#include <context_action_framework/VisionDetectionResponse.h>


namespace context_action_framework
{

struct VisionDetection
{

typedef VisionDetectionRequest Request;
typedef VisionDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VisionDetection
} // namespace context_action_framework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::context_action_framework::VisionDetection > {
  static const char* value()
  {
    return "11960e268b9d7417534a4507aec91a66";
  }

  static const char* value(const ::context_action_framework::VisionDetection&) { return value(); }
};

template<>
struct DataType< ::context_action_framework::VisionDetection > {
  static const char* value()
  {
    return "context_action_framework/VisionDetection";
  }

  static const char* value(const ::context_action_framework::VisionDetection&) { return value(); }
};


// service_traits::MD5Sum< ::context_action_framework::VisionDetectionRequest> should match
// service_traits::MD5Sum< ::context_action_framework::VisionDetection >
template<>
struct MD5Sum< ::context_action_framework::VisionDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::context_action_framework::VisionDetection >::value();
  }
  static const char* value(const ::context_action_framework::VisionDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::context_action_framework::VisionDetectionRequest> should match
// service_traits::DataType< ::context_action_framework::VisionDetection >
template<>
struct DataType< ::context_action_framework::VisionDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::context_action_framework::VisionDetection >::value();
  }
  static const char* value(const ::context_action_framework::VisionDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::context_action_framework::VisionDetectionResponse> should match
// service_traits::MD5Sum< ::context_action_framework::VisionDetection >
template<>
struct MD5Sum< ::context_action_framework::VisionDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::context_action_framework::VisionDetection >::value();
  }
  static const char* value(const ::context_action_framework::VisionDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::context_action_framework::VisionDetectionResponse> should match
// service_traits::DataType< ::context_action_framework::VisionDetection >
template<>
struct DataType< ::context_action_framework::VisionDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::context_action_framework::VisionDetection >::value();
  }
  static const char* value(const ::context_action_framework::VisionDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTEXT_ACTION_FRAMEWORK_MESSAGE_VISIONDETECTION_H
