// Generated by gencpp from file ros_vision_pipeline/ColourDepth.msg
// DO NOT EDIT!


#ifndef ROS_VISION_PIPELINE_MESSAGE_COLOURDEPTH_H
#define ROS_VISION_PIPELINE_MESSAGE_COLOURDEPTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace ros_vision_pipeline
{
template <class ContainerAllocator>
struct ColourDepth_
{
  typedef ColourDepth_<ContainerAllocator> Type;

  ColourDepth_()
    : colour_image()
    , depth_image()  {
    }
  ColourDepth_(const ContainerAllocator& _alloc)
    : colour_image(_alloc)
    , depth_image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _colour_image_type;
  _colour_image_type colour_image;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_image_type;
  _depth_image_type depth_image;





  typedef boost::shared_ptr< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> const> ConstPtr;

}; // struct ColourDepth_

typedef ::ros_vision_pipeline::ColourDepth_<std::allocator<void> > ColourDepth;

typedef boost::shared_ptr< ::ros_vision_pipeline::ColourDepth > ColourDepthPtr;
typedef boost::shared_ptr< ::ros_vision_pipeline::ColourDepth const> ColourDepthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator1> & lhs, const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator2> & rhs)
{
  return lhs.colour_image == rhs.colour_image &&
    lhs.depth_image == rhs.depth_image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator1> & lhs, const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_vision_pipeline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c674a567e9981979126deef6a4d60467";
  }

  static const char* value(const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc674a567e9981979ULL;
  static const uint64_t static_value2 = 0x126deef6a4d60467ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision_pipeline/ColourDepth";
  }

  static const char* value(const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image colour_image\n"
"sensor_msgs/Image depth_image\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.colour_image);
      stream.next(m.depth_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColourDepth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision_pipeline::ColourDepth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vision_pipeline::ColourDepth_<ContainerAllocator>& v)
  {
    s << indent << "colour_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.colour_image);
    s << indent << "depth_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_PIPELINE_MESSAGE_COLOURDEPTH_H
