// Generated by gencpp from file ros_vision_pipeline/DetectionResponse.msg
// DO NOT EDIT!


#ifndef ROS_VISION_PIPELINE_MESSAGE_DETECTIONRESPONSE_H
#define ROS_VISION_PIPELINE_MESSAGE_DETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace ros_vision_pipeline
{
template <class ContainerAllocator>
struct DetectionResponse_
{
  typedef DetectionResponse_<ContainerAllocator> Type;

  DetectionResponse_()
    : success(false)
    , image()
    , detections()  {
    }
  DetectionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , image(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionResponse_

typedef ::ros_vision_pipeline::DetectionResponse_<std::allocator<void> > DetectionResponse;

typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionResponse > DetectionResponsePtr;
typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionResponse const> DetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator1> & lhs, const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.image == rhs.image &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator1> & lhs, const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_vision_pipeline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e23fc2624ba0a7cfc8ed0d73a73b6fae";
  }

  static const char* value(const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe23fc2624ba0a7cfULL;
  static const uint64_t static_value2 = 0xc8ed0d73a73b6faeULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision_pipeline/DetectionResponse";
  }

  static const char* value(const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"sensor_msgs/Image image\n"
"string detections\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.image);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vision_pipeline::DetectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "detections: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detections);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_PIPELINE_MESSAGE_DETECTIONRESPONSE_H
