// Generated by gencpp from file ros_vision_pipeline/DetectionRequest.msg
// DO NOT EDIT!


#ifndef ROS_VISION_PIPELINE_MESSAGE_DETECTIONREQUEST_H
#define ROS_VISION_PIPELINE_MESSAGE_DETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vision_pipeline
{
template <class ContainerAllocator>
struct DetectionRequest_
{
  typedef DetectionRequest_<ContainerAllocator> Type;

  DetectionRequest_()
    {
    }
  DetectionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionRequest_

typedef ::ros_vision_pipeline::DetectionRequest_<std::allocator<void> > DetectionRequest;

typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionRequest > DetectionRequestPtr;
typedef boost::shared_ptr< ::ros_vision_pipeline::DetectionRequest const> DetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ros_vision_pipeline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision_pipeline/DetectionRequest";
  }

  static const char* value(const ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ros_vision_pipeline::DetectionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_PIPELINE_MESSAGE_DETECTIONREQUEST_H
