(cl:in-package context_action_framework-msg)
(cl:export '(ID-VAL
          ID
          TRACKING_ID-VAL
          TRACKING_ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          TF_PX-VAL
          TF_PX
          BOX_PX-VAL
          BOX_PX
          OBB_PX-VAL
          OBB_PX
          CENTER_PX-VAL
          CENTER_PX
          POLYGON_PX-VAL
          POLYGON_PX
          TF-VAL
          TF
          BOX-VAL
          BOX
          OBB-VAL
          OBB
          CENTER-VAL
          CENTER
          POLYGON-VAL
          POLYGON
          OBB_3D-VAL
          OBB_3D
))